version: "3.8"

services:
  db_postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/database.env
    container_name: postgres_db_container

  backend_python:
    build: .
    volumes:
      - .:/code/
    ports:
      - '8100:8000'
    container_name: blog_api_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db_postgres
    env_file:
      - ./env/.env
